// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReversiMvcApp.Data;

namespace ReversiMvcApp.Migrations.SpellenDb
{
    [DbContext(typeof(SpellenDbContext))]
    partial class SpellenDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ReversiMvcApp.Models.Spel", b =>
                {
                    b.Property<string>("token")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("aanDeBeurt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bordString")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("omschrijving")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("token");

                    b.ToTable("Spellen");
                });
#pragma warning restore 612, 618
        }
    }
}
